language: cpp

env:
  - tbs_arch=x86
  - tbs_arch=x64

os:
  - linux
  - osx

before_install:
  - '[ "$tbs_arch" = "x86" ] && sudo apt-get update -qq'
  - '[ "$tbs_arch" = "x86" ] && sudo apt-get -y install gcc-multilib'

script:
  - ./thumbs make
  - ./thumbs check
