language: cpp

env:
  - tbs_arch=x86
  - tbs_arch=x64

os:
  - linux
  - osx

before_install:
  - '([ "$tbs_arch" = "x86" ] && sudo apt-get update -qq) || true'
  - '([ "$tbs_arch" = "x86" ] && sudo apt-get -y install gcc-multilib) || true'

script:
  - ./thumbs make
  - ./thumbs check
