shallow_clone: true


environment:
  # settings
  static_runtime: 1
  
  static_gcargs: -DCMAKE_SHARED_LINKER_FLAGS=-static
  static_vcargs:
  #static_vcargs: -DCMAKE_C_FLAGS_RELEASE=/MT
  # ^ don't.
  
  
  matrix:
    - build_platform: "x86"
      build_compiler: "msvc"
    
    - build_platform: "x64"
      build_compiler: "msvc"
    
    - build_platform: "arm"
      build_compiler: "msvc"
    
    - build_platform: "x86"
      build_compiler: "mingw"
    
    - build_platform: "x64"
      build_compiler: "mingw"



install:
  - ps: if($env:build_platform -eq 'x64') {
          $env:vcvar_arg = 'x86_amd64';
          $env:vc_cm_arg = 'Visual Studio 12 Win64';
        }
        elseif($env:build_platform -eq 'x86') {
          $env:vcvar_arg = 'x86';
          $env:vc_cm_arg = 'Visual Studio 12';
        }
        elseif($env:build_platform -eq 'arm') {
          $env:vcvar_arg = 'x86_arm';
          $env:vc_cm_arg = 'Visual Studio 12 ARM';
        }
  
  
  # get common functions
  - git clone https://github.com/imazen/gd-appveyor-helpers
  - ps: . .\gd-appveyor-helpers\appveyor_funcs.ps1
  
  # get cmakems (C:\cmakems)
  - ps: if($env:build_compiler -eq 'msvc' -and $env:build_platform -eq 'arm') {
      invoke 'curl' '-L -o cmakems.exe "http://libgd.blob.core.windows.net/cmakems/cmake-3.0.20140929-win32-x86.exe"';
      iex 'cmakems.exe /S /D=C:\cmakems';
      $env:path = "C:\cmakems;$($env:path)"; }
  
  # get mingw-w64 (C:\mingw64)
  - ps: if($env:build_compiler -eq 'mingw' -and $env:build_platform -eq 'x64') {
      invoke 'curl' '-L -o mw64.7z "http://libgd.blob.core.windows.net/mingw/x86_64-4.9.1-release-posix-seh-rt_v3-rev1.7z"';
      invoke '7z' 'x -oC:\ mw64.7z'; }
  
  # sh is breaking mingw builds; remove
  - for %%i in (sh.exe) do @del "%%~$PATH:i"



build_script:
  
  # build msvc
  
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall" %vcvar_arg%'
  
  - SET zip=zlib-msvc12-%build_platform%.zip
  - SET cmake_cmd=cmake -G "%vc_cm_arg%"
  - if [%static_runtime%]==[1] SET cmake_cmd=%cmake_cmd% %static_vcargs%
  
  - if [%build_compiler%]==[msvc] (
      %cmake_cmd% &&
      msbuild zlib.sln /p:Configuration=Release /v:m &&
      7z a %zip% .\Release\zlib.dll .\Release\zlib.lib .\Release\zlib_static.lib zconf.h zlib.h zutil.h &&
      appveyor PushArtifact %zip%
    )
  
  - ps: if(Test-Path $env:zip) { zip2nuget $env:zip "zlib-$($env:build_compiler)-$($env:build_platform)" }
  
  
  
  # build mingw
  
  - if [%build_compiler%]==[mingw] if [%build_platform%]==[x86] SET PATH=C:\MinGW\bin;%PATH%
  - if [%build_compiler%]==[mingw] if [%build_platform%]==[x64] SET PATH=C:\mingw64\bin;%PATH%
  
  - SET zip=zlib-mingw-%build_platform%.zip
  - SET cmake_cmd=cmake -G "MinGW Makefiles"
  - if [%static_runtime%]==[1] SET cmake_cmd=%cmake_cmd% %static_gcargs%
  
  - if [%build_compiler%]==[mingw] (
      %cmake_cmd% &&
      mingw32-make &&
      7z a %zip% libz.a libz.dll libz.dll.a zconf.h zlib.h zutil.h &&
      appveyor PushArtifact %zip%
    )
  
  - ps: if(Test-Path $env:zip) { zip2nuget $env:zip "zlib-$($env:build_compiler)-$($env:build_platform)" }



test_script:
  - SET fail=0
  - ctest -C Release || SET fail=1 & ver > nul
  - ps: Push-Ctest-Results '.'
  - ps: Push-AppveyorArtifact Testing\Temporary\LastTest.log
  - exit %fail%


on_success:
  - ps: Push-AppveyorArtifact *.nupkg
